version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6378:6378"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=circle
      - POSTGRES_PASSWORD=circle123456789
      - POSTGRES_DB=ucb_payment


volumes:
  postgres_data:
